apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tor-proxy
spec:
  revisionHistoryLimit: 1
  replicas: 10
  template:
    metadata:
      labels:
        app: tor-proxy
    spec:
      containers:
      - image: dperson/torproxy
        name: tor-proxy
        ports:
        - containerPort: 8118